apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2ray-exporter
spec:
  selector:
    matchLabels: {} # Managed by Kustomize
  template:
    metadata:
      labels: {} # Managed by Kustomize
    spec:
      containers:
        - name: v2ray-exporter
          image: wi1dcard/v2ray-exporter
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
          ports:
            - name: metrics
              containerPort: 9550
